services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: lifeu_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel

  nginx:
    image: nginx:latest
    container_name: lifeu_nginx
    restart: unless-stopped
    ports:
      - "3020:3020"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
    external: true
    name: mariadb_default
