version: "3.9"

networks:
  laravel:


volumes:
  mysql_data: # Gunakan named volume untuk MySQL
  laravel_src:
    # Volume untuk source code Laravel

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "3001:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4036:3306"
    volumes:
      - mysql_data:/var/lib/mysql # Named volume untuk database
    environment:
      MYSQL_ROOT_PASSWORD: Astelo13091999$
      MYSQL_DATABASE: smarthome
      MYSQL_USER: root
      MYSQL_PASSWORD: Astelo13091999$
    networks:
      - laravel

  php:
    image: php:8.2-fpm # Gunakan PHP-FPM agar bisa bekerja dengan Nginx
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel
